recipe: default.v1
language: zh

pipeline:
  - name: JiebaTokenizer
    dictionary_path: “~/dicts/myDict.txt"
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 5
  - name: DIETClassifier
    epochs: 190
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 190
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.3
    ambiquity_threshold: 0.1
policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 190
  - name: TEDPolicy
    max_history: 5
    epochs: 190
    constrain_similarities: true
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"

assistant_id: 20230830-111444-white-button